# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
    
    - uses: actions/checkout@v4
      with:
        path: main
        
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      working-directory: main
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start Uvicorn
      working-directory: main
      run: uvicorn app.main:app --host 0.0.0.0 --port 8080 &
      shell: bash
        
    - name: Build with Maven
      working-directory: main
      run: mvn test
